"""add_setup_tokens_and_tenant_sso_config_tables

Revision ID: 5e69f529b2dc
Revises: c09370151a9f
Create Date: 2025-12-13 22:50:59.956201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e69f529b2dc'
down_revision: Union[str, Sequence[str], None] = 'c09370151a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signup_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signup_id'], ['signups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setup_tokens_expires_at'), 'setup_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_setup_tokens_id'), 'setup_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_setup_tokens_signup_id'), 'setup_tokens', ['signup_id'], unique=False)
    op.create_index(op.f('ix_setup_tokens_token'), 'setup_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_setup_tokens_user_id'), 'setup_tokens', ['user_id'], unique=False)
    op.create_table('tenant_sso_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_url', sa.String(length=500), nullable=True),
    sa.Column('entity_id', sa.String(length=500), nullable=True),
    sa.Column('sso_url', sa.String(length=500), nullable=True),
    sa.Column('x509_certificate', sa.String(length=5000), nullable=True),
    sa.Column('oidc_client_id', sa.String(length=255), nullable=True),
    sa.Column('oidc_client_secret', sa.String(length=500), nullable=True),
    sa.Column('oidc_discovery_url', sa.String(length=500), nullable=True),
    sa.Column('oidc_redirect_uri', sa.String(length=500), nullable=True),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('config_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_sso_configs_id'), 'tenant_sso_configs', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_sso_configs_tenant_id'), 'tenant_sso_configs', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_sso_configs_tenant_id'), table_name='tenant_sso_configs')
    op.drop_index(op.f('ix_tenant_sso_configs_id'), table_name='tenant_sso_configs')
    op.drop_table('tenant_sso_configs')
    op.drop_index(op.f('ix_setup_tokens_user_id'), table_name='setup_tokens')
    op.drop_index(op.f('ix_setup_tokens_token'), table_name='setup_tokens')
    op.drop_index(op.f('ix_setup_tokens_signup_id'), table_name='setup_tokens')
    op.drop_index(op.f('ix_setup_tokens_id'), table_name='setup_tokens')
    op.drop_index(op.f('ix_setup_tokens_expires_at'), table_name='setup_tokens')
    op.drop_table('setup_tokens')
    # ### end Alembic commands ###
