"""implement multi-tenant auth model with 4 tables

Revision ID: 8850c98ed5f8
Revises: c5fbe12d9919
Create Date: 2025-12-11 22:18:27.940770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8850c98ed5f8'
down_revision: Union[str, Sequence[str], None] = 'c5fbe12d9919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_algo', sa.String(length=50), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_email'), 'auth_identities', ['email'], unique=False)
    op.create_index(op.f('ix_auth_identities_id'), 'auth_identities', ['id'], unique=False)
    op.create_index(op.f('ix_auth_identities_provider'), 'auth_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('user_tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_user_tenant')
    )
    op.create_index(op.f('ix_user_tenants_id'), 'user_tenants', ['id'], unique=False)
    op.create_index(op.f('ix_user_tenants_tenant_id'), 'user_tenants', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_tenants_user_id'), 'user_tenants', ['user_id'], unique=False)
    # Add updated_at to tenants (with default for existing rows)
    op.add_column('tenants', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE tenants SET updated_at = created_at WHERE updated_at IS NULL")
    op.alter_column('tenants', 'updated_at', nullable=False)
    
    # Migrate users table
    # First add new columns as nullable
    op.add_column('users', sa.Column('primary_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_platform_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Migrate data: copy email to primary_email
    op.execute("UPDATE users SET primary_email = email WHERE primary_email IS NULL")
    op.execute("UPDATE users SET is_platform_admin = false WHERE is_platform_admin IS NULL")
    op.execute("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL")
    
    # Now make them non-nullable
    op.alter_column('users', 'primary_email', nullable=False)
    op.alter_column('users', 'is_platform_admin', nullable=False)
    op.alter_column('users', 'updated_at', nullable=False)
    
    # Migrate user-tenant relationships before dropping tenant_id
    # Create UserTenant records for existing users
    op.execute("""
        INSERT INTO user_tenants (id, user_id, tenant_id, role, is_default, created_at)
        SELECT 
            gen_random_uuid(),
            users.id,
            users.tenant_id,
            users.role,
            true,
            users.created_at
        FROM users
        WHERE users.tenant_id IS NOT NULL
    """)
    
    # Create AuthIdentity records for existing users (dev provider)
    op.execute("""
        INSERT INTO auth_identities (id, user_id, provider, provider_subject, email, email_verified, created_at)
        SELECT 
            gen_random_uuid(),
            users.id,
            'dev',
            users.email,
            users.email,
            true,
            users.created_at
        FROM users
    """)
    
    # Now drop old columns and indexes
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.create_index(op.f('ix_users_primary_email'), 'users', ['primary_email'], unique=True)
    op.drop_constraint(op.f('users_tenant_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'tenant_id')
    op.drop_column('users', 'email')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_tenant_id_fkey'), 'users', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_primary_email'), table_name='users')
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_platform_admin')
    op.drop_column('users', 'primary_email')
    op.drop_column('tenants', 'updated_at')
    op.drop_index(op.f('ix_user_tenants_user_id'), table_name='user_tenants')
    op.drop_index(op.f('ix_user_tenants_tenant_id'), table_name='user_tenants')
    op.drop_index(op.f('ix_user_tenants_id'), table_name='user_tenants')
    op.drop_table('user_tenants')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_provider'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_id'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_email'), table_name='auth_identities')
    op.drop_table('auth_identities')
    # ### end Alembic commands ###
