"""add signups table

Revision ID: ab5fd7c8ed6c
Revises: d28a462d63d7
Create Date: 2025-12-13 17:39:36.584813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab5fd7c8ed6c'
down_revision: Union[str, Sequence[str], None] = 'd28a462d63d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_domain', sa.String(length=255), nullable=True),
    sa.Column('requested_auth_mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('signup_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signups_company_domain'), 'signups', ['company_domain'], unique=False)
    op.create_index(op.f('ix_signups_email'), 'signups', ['email'], unique=False)
    op.create_index(op.f('ix_signups_id'), 'signups', ['id'], unique=False)
    op.create_index(op.f('ix_signups_membership_id'), 'signups', ['membership_id'], unique=False)
    op.create_index(op.f('ix_signups_status'), 'signups', ['status'], unique=False)
    op.create_index(op.f('ix_signups_tenant_id'), 'signups', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_signups_user_id'), 'signups', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signups_user_id'), table_name='signups')
    op.drop_index(op.f('ix_signups_tenant_id'), table_name='signups')
    op.drop_index(op.f('ix_signups_status'), table_name='signups')
    op.drop_index(op.f('ix_signups_membership_id'), table_name='signups')
    op.drop_index(op.f('ix_signups_id'), table_name='signups')
    op.drop_index(op.f('ix_signups_email'), table_name='signups')
    op.drop_index(op.f('ix_signups_company_domain'), table_name='signups')
    op.drop_table('signups')
    # ### end Alembic commands ###
