"""add_rejected_at_to_signups

Revision ID: c09370151a9f
Revises: ab5fd7c8ed6c
Create Date: 2025-12-13 20:45:11.280982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c09370151a9f'
down_revision: Union[str, Sequence[str], None] = 'ab5fd7c8ed6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signups', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signups', 'rejected_at')
    # ### end Alembic commands ###
