"""add_project_test_attribute_overrides_table

Revision ID: d46d61482b1f
Revises: e88d93747af
Create Date: 2025-12-20 12:58:25.361261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd46d61482b1f'
down_revision: Union[str, Sequence[str], None] = 'e88d93747af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('version_num', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Generic version history table for entity snapshots'
    )
    op.create_index(op.f('ix_entity_versions_changed_by_membership_id'), 'entity_versions', ['changed_by_membership_id'], unique=False)
    op.create_index(op.f('ix_entity_versions_entity_id'), 'entity_versions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_versions_id'), 'entity_versions', ['id'], unique=False)
    op.create_index(op.f('ix_entity_versions_tenant_id'), 'entity_versions', ['tenant_id'], unique=False)
    op.create_table('signups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_domain', sa.String(length=255), nullable=True),
    sa.Column('requested_auth_mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('signup_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('membership_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signups_company_domain'), 'signups', ['company_domain'], unique=False)
    op.create_index(op.f('ix_signups_email'), 'signups', ['email'], unique=False)
    op.create_index(op.f('ix_signups_id'), 'signups', ['id'], unique=False)
    op.create_index(op.f('ix_signups_membership_id'), 'signups', ['membership_id'], unique=False)
    op.create_index(op.f('ix_signups_status'), 'signups', ['status'], unique=False)
    op.create_index(op.f('ix_signups_tenant_id'), 'signups', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_signups_user_id'), 'signups', ['user_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primary_email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_primary_email'), 'users', ['primary_email'], unique=True)
    op.create_table('auth_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_algo', sa.String(length=50), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_provider_subject')
    )
    op.create_index(op.f('ix_auth_identities_email'), 'auth_identities', ['email'], unique=False)
    op.create_index(op.f('ix_auth_identities_id'), 'auth_identities', ['id'], unique=False)
    op.create_index(op.f('ix_auth_identities_provider'), 'auth_identities', ['provider'], unique=False)
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('setup_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('signup_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signup_id'], ['signups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setup_tokens_expires_at'), 'setup_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_setup_tokens_id'), 'setup_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_setup_tokens_signup_id'), 'setup_tokens', ['signup_id'], unique=False)
    op.create_index(op.f('ix_setup_tokens_token'), 'setup_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_setup_tokens_user_id'), 'setup_tokens', ['user_id'], unique=False)
    op.create_table('tenant_sso_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('metadata_url', sa.String(length=500), nullable=True),
    sa.Column('entity_id', sa.String(length=500), nullable=True),
    sa.Column('sso_url', sa.String(length=500), nullable=True),
    sa.Column('x509_certificate', sa.String(length=5000), nullable=True),
    sa.Column('oidc_client_id', sa.String(length=255), nullable=True),
    sa.Column('oidc_client_secret', sa.String(length=500), nullable=True),
    sa.Column('oidc_discovery_url', sa.String(length=500), nullable=True),
    sa.Column('oidc_redirect_uri', sa.String(length=500), nullable=True),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('config_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_sso_configs_id'), 'tenant_sso_configs', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_sso_configs_tenant_id'), 'tenant_sso_configs', ['tenant_id'], unique=True)
    op.create_table('user_tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_user_tenant')
    )
    op.create_index(op.f('ix_user_tenants_id'), 'user_tenants', ['id'], unique=False)
    op.create_index(op.f('ix_user_tenants_tenant_id'), 'user_tenants', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_tenants_user_id'), 'user_tenants', ['user_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('scope_rationale', sa.String(length=1000), nullable=True),
    sa.Column('business_owner_membership_id', sa.UUID(), nullable=True),
    sa.Column('it_owner_membership_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['business_owner_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['it_owner_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Applications are tenant-owned business applications'
    )
    op.create_index(op.f('ix_applications_business_owner_membership_id'), 'applications', ['business_owner_membership_id'], unique=False)
    op.create_index(op.f('ix_applications_created_by_membership_id'), 'applications', ['created_by_membership_id'], unique=False)
    op.create_index(op.f('ix_applications_deleted_at'), 'applications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_applications_deleted_by_membership_id'), 'applications', ['deleted_by_membership_id'], unique=False)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_it_owner_membership_id'), 'applications', ['it_owner_membership_id'], unique=False)
    op.create_index(op.f('ix_applications_tenant_id'), 'applications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_applications_updated_by_membership_id'), 'applications', ['updated_by_membership_id'], unique=False)
    op.create_index('ux_applications_tenant_name_active', 'applications', ['tenant_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('controls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by_membership_id', sa.UUID(), nullable=False),
    sa.Column('control_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('risk_rating', sa.String(length=50), nullable=True),
    sa.Column('control_type', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('is_key', sa.Boolean(), nullable=False),
    sa.Column('is_automated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Controls are tenant-owned SOX controls'
    )
    op.create_index(op.f('ix_controls_created_by_membership_id'), 'controls', ['created_by_membership_id'], unique=False)
    op.create_index(op.f('ix_controls_deleted_at'), 'controls', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_controls_deleted_by_membership_id'), 'controls', ['deleted_by_membership_id'], unique=False)
    op.create_index(op.f('ix_controls_id'), 'controls', ['id'], unique=False)
    op.create_index(op.f('ix_controls_tenant_id'), 'controls', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_controls_updated_by_membership_id'), 'controls', ['updated_by_membership_id'], unique=False)
    op.create_index('ux_controls_tenant_code_active', 'controls', ['tenant_id', 'control_code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by_membership_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Projects are tenant-owned audit engagements'
    )
    op.create_index(op.f('ix_projects_created_by_membership_id'), 'projects', ['created_by_membership_id'], unique=False)
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_deleted_by_membership_id'), 'projects', ['deleted_by_membership_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_projects_updated_by_membership_id'), 'projects', ['updated_by_membership_id'], unique=False)
    op.create_table('control_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_membership_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['removed_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Join table linking controls to applications with effective dating and tenant isolation'
    )
    op.create_index(op.f('ix_control_applications_added_by_membership_id'), 'control_applications', ['added_by_membership_id'], unique=False)
    op.create_index(op.f('ix_control_applications_application_id'), 'control_applications', ['application_id'], unique=False)
    op.create_index(op.f('ix_control_applications_control_id'), 'control_applications', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_applications_id'), 'control_applications', ['id'], unique=False)
    op.create_index(op.f('ix_control_applications_removed_at'), 'control_applications', ['removed_at'], unique=False)
    op.create_index(op.f('ix_control_applications_removed_by_membership_id'), 'control_applications', ['removed_by_membership_id'], unique=False)
    op.create_index(op.f('ix_control_applications_tenant_id'), 'control_applications', ['tenant_id'], unique=False)
    op.create_index('ix_control_apps_tenant_application', 'control_applications', ['tenant_id', 'application_id'], unique=False)
    op.create_index('ix_control_apps_tenant_control', 'control_applications', ['tenant_id', 'control_id'], unique=False)
    op.create_index('ux_control_apps_active', 'control_applications', ['tenant_id', 'control_id', 'application_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL'))
    op.create_table('pbc_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('owner_membership_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('samples_requested', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_membership_id'], ['user_tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='PBC requests track evidence requests for control testing'
    )
    op.create_index(op.f('ix_pbc_requests_application_id'), 'pbc_requests', ['application_id'], unique=False)
    op.create_index(op.f('ix_pbc_requests_control_id'), 'pbc_requests', ['control_id'], unique=False)
    op.create_index(op.f('ix_pbc_requests_id'), 'pbc_requests', ['id'], unique=False)
    op.create_index(op.f('ix_pbc_requests_owner_membership_id'), 'pbc_requests', ['owner_membership_id'], unique=False)
    op.create_index(op.f('ix_pbc_requests_project_id'), 'pbc_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_pbc_requests_tenant_id'), 'pbc_requests', ['tenant_id'], unique=False)
    op.create_table('project_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'application_id', name='uq_project_application_tenant'),
    comment='Join table linking projects to applications with tenant isolation'
    )
    op.create_index(op.f('ix_project_applications_application_id'), 'project_applications', ['application_id'], unique=False)
    op.create_index(op.f('ix_project_applications_id'), 'project_applications', ['id'], unique=False)
    op.create_index(op.f('ix_project_applications_project_id'), 'project_applications', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_applications_tenant_id'), 'project_applications', ['tenant_id'], unique=False)
    op.create_table('project_controls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('control_version_num', sa.Integer(), nullable=False),
    sa.Column('is_key_override', sa.Boolean(), nullable=True),
    sa.Column('frequency_override', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by_membership_id', sa.UUID(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_membership_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['removed_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Join table linking projects to controls with tenant isolation and version freezing'
    )
    op.create_index(op.f('ix_project_controls_added_by_membership_id'), 'project_controls', ['added_by_membership_id'], unique=False)
    op.create_index(op.f('ix_project_controls_control_id'), 'project_controls', ['control_id'], unique=False)
    op.create_index(op.f('ix_project_controls_deleted_at'), 'project_controls', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_project_controls_deleted_by_membership_id'), 'project_controls', ['deleted_by_membership_id'], unique=False)
    op.create_index(op.f('ix_project_controls_id'), 'project_controls', ['id'], unique=False)
    op.create_index(op.f('ix_project_controls_project_id'), 'project_controls', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_controls_removed_at'), 'project_controls', ['removed_at'], unique=False)
    op.create_index(op.f('ix_project_controls_removed_by_membership_id'), 'project_controls', ['removed_by_membership_id'], unique=False)
    op.create_index('ix_project_controls_tenant_control', 'project_controls', ['tenant_id', 'control_id'], unique=False)
    op.create_index(op.f('ix_project_controls_tenant_id'), 'project_controls', ['tenant_id'], unique=False)
    op.create_index('ix_project_controls_tenant_project', 'project_controls', ['tenant_id', 'project_id'], unique=False)
    op.create_index(op.f('ix_project_controls_updated_by_membership_id'), 'project_controls', ['updated_by_membership_id'], unique=False)
    op.create_index('ux_project_controls_active', 'project_controls', ['tenant_id', 'project_id', 'control_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL'))
    op.create_table('test_attributes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('control_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('test_procedure', sa.Text(), nullable=True),
    sa.Column('expected_evidence', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_membership_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Test attributes define test procedures and expected evidence for controls'
    )
    op.create_index(op.f('ix_test_attributes_control_id'), 'test_attributes', ['control_id'], unique=False)
    op.create_index(op.f('ix_test_attributes_created_by_membership_id'), 'test_attributes', ['created_by_membership_id'], unique=False)
    op.create_index(op.f('ix_test_attributes_deleted_at'), 'test_attributes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_test_attributes_deleted_by_membership_id'), 'test_attributes', ['deleted_by_membership_id'], unique=False)
    op.create_index(op.f('ix_test_attributes_id'), 'test_attributes', ['id'], unique=False)
    op.create_index(op.f('ix_test_attributes_tenant_id'), 'test_attributes', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_test_attributes_updated_by_membership_id'), 'test_attributes', ['updated_by_membership_id'], unique=False)
    op.create_index('ux_test_attributes_active_code', 'test_attributes', ['tenant_id', 'control_id', 'code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('project_control_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_control_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('application_version_num', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by_membership_id', sa.UUID(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_by_membership_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_control_id'], ['project_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['removed_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Join table linking project controls to applications with tenant isolation and version freezing'
    )
    op.create_index('ix_pca_tenant_application', 'project_control_applications', ['tenant_id', 'application_id'], unique=False)
    op.create_index('ix_pca_tenant_project_control', 'project_control_applications', ['tenant_id', 'project_control_id'], unique=False)
    op.create_index(op.f('ix_project_control_applications_added_by_membership_id'), 'project_control_applications', ['added_by_membership_id'], unique=False)
    op.create_index(op.f('ix_project_control_applications_application_id'), 'project_control_applications', ['application_id'], unique=False)
    op.create_index(op.f('ix_project_control_applications_id'), 'project_control_applications', ['id'], unique=False)
    op.create_index(op.f('ix_project_control_applications_project_control_id'), 'project_control_applications', ['project_control_id'], unique=False)
    op.create_index(op.f('ix_project_control_applications_removed_at'), 'project_control_applications', ['removed_at'], unique=False)
    op.create_index(op.f('ix_project_control_applications_removed_by_membership_id'), 'project_control_applications', ['removed_by_membership_id'], unique=False)
    op.create_index(op.f('ix_project_control_applications_tenant_id'), 'project_control_applications', ['tenant_id'], unique=False)
    op.create_index('ux_project_control_apps_active', 'project_control_applications', ['tenant_id', 'project_control_id', 'application_id'], unique=True, postgresql_where=sa.text('removed_at IS NULL'))
    op.create_table('project_test_attribute_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_control_id', sa.UUID(), nullable=False),
    sa.Column('test_attribute_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('base_test_attribute_version_num', sa.Integer(), nullable=False),
    sa.Column('name_override', sa.Text(), nullable=True),
    sa.Column('frequency_override', sa.Text(), nullable=True),
    sa.Column('procedure_override', sa.Text(), nullable=True),
    sa.Column('expected_evidence_override', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_control_id'], ['project_controls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_attribute_id'], ['test_attributes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_membership_id'], ['user_tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Project-level overrides for test attributes with tenant isolation and version freezing'
    )
    op.create_index(op.f('ix_project_test_attribute_overrides_application_id'), 'project_test_attribute_overrides', ['application_id'], unique=False)
    op.create_index(op.f('ix_project_test_attribute_overrides_created_by_membership_id'), 'project_test_attribute_overrides', ['created_by_membership_id'], unique=False)
    op.create_index(op.f('ix_project_test_attribute_overrides_deleted_at'), 'project_test_attribute_overrides', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_project_test_attribute_overrides_deleted_by_membership_id'), 'project_test_attribute_overrides', ['deleted_by_membership_id'], unique=False)
    op.create_index(op.f('ix_project_test_attribute_overrides_id'), 'project_test_attribute_overrides', ['id'], unique=False)
    op.create_index(op.f('ix_project_test_attribute_overrides_project_control_id'), 'project_test_attribute_overrides', ['project_control_id'], unique=False)
    op.create_index(op.f('ix_project_test_attribute_overrides_tenant_id'), 'project_test_attribute_overrides', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_project_test_attribute_overrides_test_attribute_id'), 'project_test_attribute_overrides', ['test_attribute_id'], unique=False)
    op.create_index(op.f('ix_project_test_attribute_overrides_updated_by_membership_id'), 'project_test_attribute_overrides', ['updated_by_membership_id'], unique=False)
    op.create_index('ix_ptao_tenant_project_control', 'project_test_attribute_overrides', ['tenant_id', 'project_control_id'], unique=False)
    op.create_index('ix_ptao_tenant_test_attribute', 'project_test_attribute_overrides', ['tenant_id', 'test_attribute_id'], unique=False)
    op.create_index('ux_ptao_active_app', 'project_test_attribute_overrides', ['tenant_id', 'project_control_id', 'application_id', 'test_attribute_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND application_id IS NOT NULL'))
    op.create_index('ux_ptao_active_global', 'project_test_attribute_overrides', ['tenant_id', 'project_control_id', 'test_attribute_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND application_id IS NULL'))
    
    # Ensure the generic version trigger function exists (should already exist from earlier migration, but create if missing)
    op.execute("""
        CREATE OR REPLACE FUNCTION audit_capture_entity_version()
        RETURNS TRIGGER AS $$
        DECLARE
            v_operation TEXT;
            v_changed_by_membership_id UUID;
            v_entity_type TEXT;
        BEGIN
            -- Determine entity_type from table name
            v_entity_type := TG_TABLE_NAME;
            
            -- Determine operation
            IF TG_OP = 'DELETE' THEN
                v_operation := 'DELETE';
                v_changed_by_membership_id := NULL;
            ELSE
                -- UPDATE operation
                IF OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL THEN
                    -- Soft delete: OLD was active, NEW is deleted
                    v_operation := 'DELETE';
                    v_changed_by_membership_id := NEW.deleted_by_membership_id;
                ELSE
                    -- Regular update
                    v_operation := 'UPDATE';
                    v_changed_by_membership_id := NEW.updated_by_membership_id;
                END IF;
            END IF;
            
            -- Insert snapshot into entity_versions
            INSERT INTO entity_versions (
                tenant_id,
                entity_type,
                entity_id,
                operation,
                version_num,
                valid_from,
                valid_to,
                changed_by_membership_id,
                data
            ) VALUES (
                OLD.tenant_id,
                v_entity_type,
                OLD.id,
                v_operation,
                OLD.row_version,
                COALESCE(OLD.updated_at, OLD.created_at),
                NOW(),
                v_changed_by_membership_id,
                to_jsonb(OLD)
            );
            
            -- Return appropriate record
            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            ELSE
                RETURN NEW;
            END IF;
        END;
        $$ LANGUAGE plpgsql;
    """)
    
    # Create trigger for project_test_attribute_overrides version history
    op.execute("""
        CREATE TRIGGER trigger_audit_capture_project_test_attribute_override_version
        BEFORE UPDATE OR DELETE ON project_test_attribute_overrides
        FOR EACH ROW
        EXECUTE FUNCTION audit_capture_entity_version();
    """)
    
    op.create_table('samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pbc_request_id', sa.UUID(), nullable=False),
    sa.Column('sample_number', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('test_notes', sa.Text(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tested_by_membership_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pbc_request_id'], ['pbc_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tested_by_membership_id'], ['user_tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Samples for control testing in audit projects'
    )
    op.create_index(op.f('ix_samples_id'), 'samples', ['id'], unique=False)
    op.create_index(op.f('ix_samples_pbc_request_id'), 'samples', ['pbc_request_id'], unique=False)
    op.create_index(op.f('ix_samples_tenant_id'), 'samples', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_samples_tested_by_membership_id'), 'samples', ['tested_by_membership_id'], unique=False)
    op.create_table('evidence_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('pbc_request_id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by_membership_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_uri', sa.String(length=512), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_file_id', sa.UUID(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pbc_request_id'], ['pbc_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_file_id'], ['evidence_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_membership_id'], ['user_tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Evidence files uploaded for PBC requests and samples'
    )
    op.create_index(op.f('ix_evidence_files_id'), 'evidence_files', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_files_pbc_request_id'), 'evidence_files', ['pbc_request_id'], unique=False)
    op.create_index(op.f('ix_evidence_files_sample_id'), 'evidence_files', ['sample_id'], unique=False)
    op.create_index(op.f('ix_evidence_files_tenant_id'), 'evidence_files', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_evidence_files_uploaded_by_membership_id'), 'evidence_files', ['uploaded_by_membership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop trigger for project_test_attribute_overrides
    op.execute("DROP TRIGGER IF EXISTS trigger_audit_capture_project_test_attribute_override_version ON project_test_attribute_overrides;")
    
    op.drop_index(op.f('ix_evidence_files_uploaded_by_membership_id'), table_name='evidence_files')
    op.drop_index(op.f('ix_evidence_files_tenant_id'), table_name='evidence_files')
    op.drop_index(op.f('ix_evidence_files_sample_id'), table_name='evidence_files')
    op.drop_index(op.f('ix_evidence_files_pbc_request_id'), table_name='evidence_files')
    op.drop_index(op.f('ix_evidence_files_id'), table_name='evidence_files')
    op.drop_table('evidence_files')
    op.drop_index(op.f('ix_samples_tested_by_membership_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_tenant_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_pbc_request_id'), table_name='samples')
    op.drop_index(op.f('ix_samples_id'), table_name='samples')
    op.drop_table('samples')
    op.drop_index('ux_ptao_active_global', table_name='project_test_attribute_overrides', postgresql_where=sa.text('deleted_at IS NULL AND application_id IS NULL'))
    op.drop_index('ux_ptao_active_app', table_name='project_test_attribute_overrides', postgresql_where=sa.text('deleted_at IS NULL AND application_id IS NOT NULL'))
    op.drop_index('ix_ptao_tenant_test_attribute', table_name='project_test_attribute_overrides')
    op.drop_index('ix_ptao_tenant_project_control', table_name='project_test_attribute_overrides')
    op.drop_index(op.f('ix_project_test_attribute_overrides_updated_by_membership_id'), table_name='project_test_attribute_overrides')
    op.drop_index(op.f('ix_project_test_attribute_overrides_test_attribute_id'), table_name='project_test_attribute_overrides')
    op.drop_index(op.f('ix_project_test_attribute_overrides_tenant_id'), table_name='project_test_attribute_overrides')
    op.drop_index(op.f('ix_project_test_attribute_overrides_project_control_id'), table_name='project_test_attribute_overrides')
    op.drop_index(op.f('ix_project_test_attribute_overrides_id'), table_name='project_test_attribute_overrides')
    op.drop_index(op.f('ix_project_test_attribute_overrides_deleted_by_membership_id'), table_name='project_test_attribute_overrides')
    op.drop_index(op.f('ix_project_test_attribute_overrides_deleted_at'), table_name='project_test_attribute_overrides')
    op.drop_index(op.f('ix_project_test_attribute_overrides_created_by_membership_id'), table_name='project_test_attribute_overrides')
    op.drop_index(op.f('ix_project_test_attribute_overrides_application_id'), table_name='project_test_attribute_overrides')
    op.drop_table('project_test_attribute_overrides')
    op.drop_index('ux_project_control_apps_active', table_name='project_control_applications', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index(op.f('ix_project_control_applications_tenant_id'), table_name='project_control_applications')
    op.drop_index(op.f('ix_project_control_applications_removed_by_membership_id'), table_name='project_control_applications')
    op.drop_index(op.f('ix_project_control_applications_removed_at'), table_name='project_control_applications')
    op.drop_index(op.f('ix_project_control_applications_project_control_id'), table_name='project_control_applications')
    op.drop_index(op.f('ix_project_control_applications_id'), table_name='project_control_applications')
    op.drop_index(op.f('ix_project_control_applications_application_id'), table_name='project_control_applications')
    op.drop_index(op.f('ix_project_control_applications_added_by_membership_id'), table_name='project_control_applications')
    op.drop_index('ix_pca_tenant_project_control', table_name='project_control_applications')
    op.drop_index('ix_pca_tenant_application', table_name='project_control_applications')
    op.drop_table('project_control_applications')
    op.drop_index('ux_test_attributes_active_code', table_name='test_attributes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_test_attributes_updated_by_membership_id'), table_name='test_attributes')
    op.drop_index(op.f('ix_test_attributes_tenant_id'), table_name='test_attributes')
    op.drop_index(op.f('ix_test_attributes_id'), table_name='test_attributes')
    op.drop_index(op.f('ix_test_attributes_deleted_by_membership_id'), table_name='test_attributes')
    op.drop_index(op.f('ix_test_attributes_deleted_at'), table_name='test_attributes')
    op.drop_index(op.f('ix_test_attributes_created_by_membership_id'), table_name='test_attributes')
    op.drop_index(op.f('ix_test_attributes_control_id'), table_name='test_attributes')
    op.drop_table('test_attributes')
    op.drop_index('ux_project_controls_active', table_name='project_controls', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index(op.f('ix_project_controls_updated_by_membership_id'), table_name='project_controls')
    op.drop_index('ix_project_controls_tenant_project', table_name='project_controls')
    op.drop_index(op.f('ix_project_controls_tenant_id'), table_name='project_controls')
    op.drop_index('ix_project_controls_tenant_control', table_name='project_controls')
    op.drop_index(op.f('ix_project_controls_removed_by_membership_id'), table_name='project_controls')
    op.drop_index(op.f('ix_project_controls_removed_at'), table_name='project_controls')
    op.drop_index(op.f('ix_project_controls_project_id'), table_name='project_controls')
    op.drop_index(op.f('ix_project_controls_id'), table_name='project_controls')
    op.drop_index(op.f('ix_project_controls_deleted_by_membership_id'), table_name='project_controls')
    op.drop_index(op.f('ix_project_controls_deleted_at'), table_name='project_controls')
    op.drop_index(op.f('ix_project_controls_control_id'), table_name='project_controls')
    op.drop_index(op.f('ix_project_controls_added_by_membership_id'), table_name='project_controls')
    op.drop_table('project_controls')
    op.drop_index(op.f('ix_project_applications_tenant_id'), table_name='project_applications')
    op.drop_index(op.f('ix_project_applications_project_id'), table_name='project_applications')
    op.drop_index(op.f('ix_project_applications_id'), table_name='project_applications')
    op.drop_index(op.f('ix_project_applications_application_id'), table_name='project_applications')
    op.drop_table('project_applications')
    op.drop_index(op.f('ix_pbc_requests_tenant_id'), table_name='pbc_requests')
    op.drop_index(op.f('ix_pbc_requests_project_id'), table_name='pbc_requests')
    op.drop_index(op.f('ix_pbc_requests_owner_membership_id'), table_name='pbc_requests')
    op.drop_index(op.f('ix_pbc_requests_id'), table_name='pbc_requests')
    op.drop_index(op.f('ix_pbc_requests_control_id'), table_name='pbc_requests')
    op.drop_index(op.f('ix_pbc_requests_application_id'), table_name='pbc_requests')
    op.drop_table('pbc_requests')
    op.drop_index('ux_control_apps_active', table_name='control_applications', postgresql_where=sa.text('removed_at IS NULL'))
    op.drop_index('ix_control_apps_tenant_control', table_name='control_applications')
    op.drop_index('ix_control_apps_tenant_application', table_name='control_applications')
    op.drop_index(op.f('ix_control_applications_tenant_id'), table_name='control_applications')
    op.drop_index(op.f('ix_control_applications_removed_by_membership_id'), table_name='control_applications')
    op.drop_index(op.f('ix_control_applications_removed_at'), table_name='control_applications')
    op.drop_index(op.f('ix_control_applications_id'), table_name='control_applications')
    op.drop_index(op.f('ix_control_applications_control_id'), table_name='control_applications')
    op.drop_index(op.f('ix_control_applications_application_id'), table_name='control_applications')
    op.drop_index(op.f('ix_control_applications_added_by_membership_id'), table_name='control_applications')
    op.drop_table('control_applications')
    op.drop_index(op.f('ix_projects_updated_by_membership_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_by_membership_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by_membership_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ux_controls_tenant_code_active', table_name='controls', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_controls_updated_by_membership_id'), table_name='controls')
    op.drop_index(op.f('ix_controls_tenant_id'), table_name='controls')
    op.drop_index(op.f('ix_controls_id'), table_name='controls')
    op.drop_index(op.f('ix_controls_deleted_by_membership_id'), table_name='controls')
    op.drop_index(op.f('ix_controls_deleted_at'), table_name='controls')
    op.drop_index(op.f('ix_controls_created_by_membership_id'), table_name='controls')
    op.drop_table('controls')
    op.drop_index('ux_applications_tenant_name_active', table_name='applications', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_applications_updated_by_membership_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_tenant_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_it_owner_membership_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_deleted_by_membership_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_deleted_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_created_by_membership_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_business_owner_membership_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_user_tenants_user_id'), table_name='user_tenants')
    op.drop_index(op.f('ix_user_tenants_tenant_id'), table_name='user_tenants')
    op.drop_index(op.f('ix_user_tenants_id'), table_name='user_tenants')
    op.drop_table('user_tenants')
    op.drop_index(op.f('ix_tenant_sso_configs_tenant_id'), table_name='tenant_sso_configs')
    op.drop_index(op.f('ix_tenant_sso_configs_id'), table_name='tenant_sso_configs')
    op.drop_table('tenant_sso_configs')
    op.drop_index(op.f('ix_setup_tokens_user_id'), table_name='setup_tokens')
    op.drop_index(op.f('ix_setup_tokens_token'), table_name='setup_tokens')
    op.drop_index(op.f('ix_setup_tokens_signup_id'), table_name='setup_tokens')
    op.drop_index(op.f('ix_setup_tokens_id'), table_name='setup_tokens')
    op.drop_index(op.f('ix_setup_tokens_expires_at'), table_name='setup_tokens')
    op.drop_table('setup_tokens')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_provider'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_id'), table_name='auth_identities')
    op.drop_index(op.f('ix_auth_identities_email'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_users_primary_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_signups_user_id'), table_name='signups')
    op.drop_index(op.f('ix_signups_tenant_id'), table_name='signups')
    op.drop_index(op.f('ix_signups_status'), table_name='signups')
    op.drop_index(op.f('ix_signups_membership_id'), table_name='signups')
    op.drop_index(op.f('ix_signups_id'), table_name='signups')
    op.drop_index(op.f('ix_signups_email'), table_name='signups')
    op.drop_index(op.f('ix_signups_company_domain'), table_name='signups')
    op.drop_table('signups')
    op.drop_index(op.f('ix_entity_versions_tenant_id'), table_name='entity_versions')
    op.drop_index(op.f('ix_entity_versions_id'), table_name='entity_versions')
    op.drop_index(op.f('ix_entity_versions_entity_id'), table_name='entity_versions')
    op.drop_index(op.f('ix_entity_versions_changed_by_membership_id'), table_name='entity_versions')
    op.drop_table('entity_versions')
    # ### end Alembic commands ###
